baseurl = 'https://sweet-brigadeiros-38834a.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'ananke'

[menu]

[[menu.main]]
name = "Home"
pageref = "/"
weight = 1

[[menu.main]]
name = "posts"
pageref = "/posts/"
weight = 2

[[menu.main]]
name = "Contact"
pageref = "/contact/"
weight = 3

