baseurl = 'https://sweet-brigadeiros-38834a.netlify.app/'
languageCode = 'en-us'
title = 'Student Parking at UKY'
theme = 'ananke'

[menu]

[[menu.main]]
name = "Home"
pageref = "/"
weight = 10

[[menu.main]]
name = "Posts"
pageref = "/posts/"
weight = 20

[[menu.main]]
name = "Contact"
pageref = "/contact/"
weight = 30

